In [62]:
import pandas as pd
import numpy as np
pd.__version__

'2.3.1'

In [33]:
data = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv")
data.head(5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [34]:
data.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [35]:
data.index

RangeIndex(start=0, stop=9704, step=1)

In [36]:
data.fuel_type.nunique()

2

In [37]:
asia =data[data.origin == 'Asia']
asia.head(3)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091

In [38]:
asia.fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

In [39]:
data.horsepower.median()

np.float64(149.0)

In [40]:
data.horsepower.mode()

0    152.0
Name: horsepower, dtype: float64

In [41]:
data.horsepower.isnull().sum()

np.int64(708)

In [44]:
most_frequent = data.horsepower.mode()[0]
most_frequent

np.float64(152.0)

In [45]:
data.horsepower = data.horsepower.fillna(most_frequent)
data.horsepower.isnull().sum()

np.int64(0)

In [46]:
data.horsepower.median()

np.float64(152.0)

In [47]:
asia.head(7)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   
34                  150            2.0       149.0     2844.227534   
38                  190            5.0       158.0     3761.994038   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
34          17.3        2014   Asia    Diesel  Front-wheel drive        0.0   
38           NaN        2019   Asia  Gasoline  Front-wheel drive        1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730  
34            15.353788  
38            11.645724

In [50]:
asia=asia[['vehicle_weight','model_year']].head(7)

In [57]:
X = asia.values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [59]:
XT = X.T
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [60]:
XTX = XT.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [71]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
inv_X = np.linalg.inv(XTX)
w= (inv_X.dot(XT)).dot(y)
w.sum()

np.float64(0.5187709081074016)