In [1]:
import pandas as pd
import numpy as np


In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10,9)

array([9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [5]:
num_list= [1,2,3,4,5,6]
a = np.array(num_list)
a

array([1, 2, 3, 4, 5, 6])

In [6]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [7]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## multidemisional array

In [8]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
multi= np.array([[1,2,3],[4,5,6],[7,8,9]])
multi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
multi[1][0]

np.int64(4)

In [12]:
 multi[:,2]

array([3, 6, 9])

## randomly generated array

In [13]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [14]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [15]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [16]:
num= np.arange(5)
num

array([0, 1, 2, 3, 4])

In [17]:
num*2

array([0, 2, 4, 6, 8])

In [18]:
num>=4

array([False, False, False, False,  True])

In [19]:
np.random.seed(2)
#c= np.random.randint(low=0,high=10, size=(5))
#c = np.array([1.0,1.3,6.0,2.0,2.5])
c=np.arange(5)
c

array([0, 1, 2, 3, 4])

In [20]:
num[num > c]

array([], dtype=int64)

In [21]:
a

array([1, 2, 3, 4, 5, 6])

In [22]:
a.min()

np.int64(1)

In [23]:
a.max()

np.int64(6)

In [24]:
a.mean()

np.float64(3.5)

## Linear Algebra

### vector operation

In [25]:
v = np.arange(5)
v

array([0, 1, 2, 3, 4])

In [26]:
u = np.arange(5)*3
u

array([ 0,  3,  6,  9, 12])

#### vector-Vector multiplication (dot product)

In [27]:
def vector_Vector_multiplication (u,v):
    assert u.shape[0]==v.shape[0]

    n=u.shape[0]
    result= 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result

vector_Vector_multiplication (u,v)

np.float64(90.0)

In [28]:
u.dot(v)

np.int64(90)

### matrix_vector multiplication

In [29]:
u = np.array([[ 1,2,3],[4,3,5],[4,7,8]])
v=np.array([4,7,9])

In [30]:
u

array([[1, 2, 3],
       [4, 3, 5],
       [4, 7, 8]])

In [31]:
def matrix_vector_multiplication (u,v):
    assert u.shape[0] == v.shape[0]
    num_rows = u.shape[0]
    result= np.zeros(num_rows)
    
    for i in range (num_rows):
        result[i]= vector_Vector_multiplication(u[i],v)

    return result
matrix_vector_multiplication (u,v)


array([ 45.,  82., 137.])

In [32]:
u.dot(v)

array([ 45,  82, 137])

### matrix_matrix_multiplication

In [33]:
u = np.array([[ 1,2,3],[4,3,5],[4,7,8]])
v=np.array([[4,7,9],[ 1,2,3],[4,7,8]])

def matrix_matrix_multiplication(u,v):
    assert u.shape[0]*v.shape[0]

    num_row = u.shape[0]
    num_col = v.shape[1]
    result = np.zeros((num_row, num_col))

    for i in range (num_col):
        vi = v[:,i]
        uvi = matrix_vector_multiplication (u,vi)
        result[:,i] = uvi

    return result

In [34]:
matrix_matrix_multiplication(u,v)

array([[ 18.,  32.,  39.],
       [ 39.,  69.,  85.],
       [ 55.,  98., 121.]])

In [35]:
u.dot(v)

array([[ 18,  32,  39],
       [ 39,  69,  85],
       [ 55,  98, 121]])

### Identity Matrix

In [36]:
I = np.eye(3)

In [37]:
v

array([[4, 7, 9],
       [1, 2, 3],
       [4, 7, 8]])

In [38]:
v.dot(I)

array([[4., 7., 9.],
       [1., 2., 3.],
       [4., 7., 8.]])

In [39]:
I.dot(v)

array([[4., 7., 9.],
       [1., 2., 3.],
       [4., 7., 8.]])

### Inverse

In [40]:
vs = v[[0,1,2]]
vs

array([[4, 7, 9],
       [1, 2, 3],
       [4, 7, 8]])

In [41]:
vs_inv = np.linalg.inv(vs)
vs_inv

array([[ 5., -7., -3.],
       [-4.,  4.,  3.],
       [ 1., -0., -1.]])

# PANDAS

### DataFrames

In [42]:
import pandas as pd


data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [43]:
df = pd.DataFrame(data, columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [44]:
data2 = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": None,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340
    }
]

In [45]:
df2=pd.DataFrame(data2)
df2

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [46]:
df_new= df2[["Make","Year","Engine HP", "Engine Cylinders"]]
df_new

Make  Year  Engine HP  Engine Cylinders
0   Nissan  1991      138.0                 4
1  Hyundai  2017        NaN                 4
2    Lotus  2010      218.0                 4
3      GMC  2017      194.0                 4
4   Nissan  2017      261.0                 6

In [47]:
df_new.Year

0    1991
1    2017
2    2010
3    2017
4    2017
Name: Year, dtype: int64

In [48]:
df_new['id'] = [1,2,3,4,5]
df_new

/tmp/ipykernel_3648/2366628218.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new['id'] = [1,2,3,4,5]


Make  Year  Engine HP  Engine Cylinders  id
0   Nissan  1991      138.0                 4   1
1  Hyundai  2017        NaN                 4   2
2    Lotus  2010      218.0                 4   3
3      GMC  2017      194.0                 4   4
4   Nissan  2017      261.0                 6   5

In [49]:
del df_new['id']
df_new

Make  Year  Engine HP  Engine Cylinders
0   Nissan  1991      138.0                 4
1  Hyundai  2017        NaN                 4
2    Lotus  2010      218.0                 4
3      GMC  2017      194.0                 4
4   Nissan  2017      261.0                 6

In [50]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [51]:
df['id'] = [1,2,3,4,5]
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

In [52]:
del df['id']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [53]:
df.index= ['a','b','c','d','e']
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [54]:
df.loc[['a','d']]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a  Nissan  Stanza  1991      138.0                 4            MANUAL   
d     GMC  Acadia  2017      194.0                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
a         sedan   2000  
d       4dr SUV  34450

In [55]:
df.iloc[['1','2']]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
c   convertible  54990

In [56]:
df= df.reset_index(drop = True)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [57]:
df[(df.Make=='Nissan') & (df.Year>=2015)]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
4  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
4        Pickup  32340

In [58]:
df.Vehicle_Style = df.Vehicle_Style.str.lower()

In [59]:
df.Vehicle_Style

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: object

In [60]:
df.Vehicle_Style.str.replace(' ','_')

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: object

In [61]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='object')

In [62]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [63]:
df.MSRP.sum()

np.int64(150930)

In [64]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

In [65]:
df.isnull()

Make  Model   Year  Engine HP  Engine Cylinders  Transmission Type  \
0  False  False  False      False             False              False   
1  False  False  False       True             False              False   
2  False  False  False      False             False              False   
3  False  False  False      False             False              False   
4  False  False  False      False             False              False   

   Vehicle_Style   MSRP  
0          False  False  
1          False  False  
2          False  False  
3          False  False  
4          False  False

In [66]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [67]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
       'Transmission Type', 'Vehicle_Style', 'MSRP'],
      dtype='object')

In [68]:
df.groupby('Transmission Type')['Engine HP'].mean()

Transmission Type
AUTOMATIC    194.000000
MANUAL       205.666667
Name: Engine HP, dtype: float64

In [70]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64